button1などの名前を修正
0429oonishi/ShoppingApplication pull request #19
Opened 2021-03-22 21:26 UTC by Reon0429-cat

[修正前]
button1, button2, button3 ...など、一見どのボタンなのかわからない命名にしていました。

[修正後]
firstPageNextButtonなど、1枚目の次へ行くためのボタンなんだとわかるように命名を変更しました。

[関連issue]
#8

2021-03-23 13:39 UTC, sakiyamaK requested changes
@0429oonishi これじゃ10を十って書き換えたのと変わりません

https://note.com/sakiyamak/n/n79560ebc116a

2021-03-23 13:39 UTC, sakiyamaK commented on ShoppingApplication/Controllers/HowToUseCalculationViewController.swift
> +        case firstPageImage
firstって1のことですから何も変わってないですね

2021-03-23 19:03 UTC, Reon0429-cat commented on ShoppingApplication/Controllers/HowToUseCalculationViewController.swift
> +        case firstPageImage
@sakiyamaK すいません、このような場合、どのように命名して良いのかわかりません。

![スクリーンショット 2021-03-24 4 03 04](https://user-images.githubusercontent.com/66917548/112203402-d777e600-8c55-11eb-847d-4468ad9c587a.png)

2021-03-24 01:58 UTC, sakiyamaK commented on ShoppingApplication/Controllers/HowToUseCalculationViewController.swift
> +        case firstPageImage
@0429oonishi 追加の説明をしているので`HowToAdd`というワードを入れたらいいんじゃないですか？

2021-03-24 02:45 UTC, Reon0429-cat commented on ShoppingApplication/Controllers/HowToUseCalculationViewController.swift
> +        case firstPageImage
@sakiyamaK ありがとうございます

2021-04-29 10:21 UTC, closed without merging